### ISSUE TITLE
Zugriffsrechte im Wiki

### ISSUE THREAD

**Issue by Circonflexe** [we-pnp/hero#4]
Da ich in den letzten Tagen doch recht viel über meinen Charakter geschrieben habe und einiges davon auch die Fragen beantwortet, die Martin in der Charakter-Checkliste voraussetzt, kam mir der Gedanke, dass es doch eigentlich unnötig kompliziert ist, mit Dateien zu arbeiten. Auch Rene sagte ja schon, dass er mittlerweile eine große Sammlung an Charakterbögen von uns rumliegen hat.

Wäre es da nicht vielleicht klüger, diese Dinge online für den Meister zugänglich zu machen? Oder sogar manche Dinge für alle zugänglich, wie z.B. meine Zusammenfassungen der Abenteuer?

Ich weiß nun nicht, welche Möglichkeiten das Wiki hier so bietet, was Zugriffsrechte angeht, aber wenn man tatsächlich einstellen kann, wer welche Wiki-Einträge lesen kann, könnten wir das doch nicht nur für unser Regelwerk nutzen, sondern eben auch Charakter- und Abenteuer- Wiki-Seiten erstellen.

Was haltet ihr von der Idee?

**Comment by ShikamaNikos** [comment]
Also ich hab nichts dagegen Charakterbögen zu bekommen. Ich würde das euch überlassen. Ich denke wenn ich die in meiner eigenen Ordnung auf dem PC habe komm ich damit besser klar. Wenn es möglicht ist das Online zu machen und das einfacher für euch ist die dann zu erstellen, können wir das auch so machen.

**Comment by we-pnp** [comment]
generell können alle unter _Code_ eigene Dateien hochladen, die sind dann aber auch für alle öffentlich. 

Spezielle Zugriffsrechte lassen sich nicht so einfach verteilen, eventuell geht das mit den teams Funktionen, da kann ich mich gerne reinarbeiten.
