### ISSUE TITLE
Neue Fragen

### ISSUE THREAD

**Issue by Circonflexe** [we-pnp/hero#5]
### Punkte, die sich aus den bisherigen To-Do-Listen ergeben:

- [x] Da wir nun auf einer Internatschule leben und wir uns für eine Schuluniform entschieden hatten - in welchem Rahmen tragen wir private Freizeitkleidung? Außerhalb der Unterrichtszeiten? Nur wenn wir das Schulgelände verlassen? Im Grunde gar nicht, außer wir sind in den 'Ferien'?
 - [x] evtl. noch allgemeine Wünsche, was unser Schulleben beinhalten sollte/könnte? Was den Aufbau unserer Stadt angeht? Oder irgendetwas Anderes Setting-betreffendes?
- [x] Gemeinsames Erstellen eines Rohlings für den Heldenbogen
- [x] Übertragen des Heldenbogens in eine PDF (nach Möglichkeit mit Script für z.B. den Wert von Willenskraft, Geschwindigkeit)
- [x] Formel für Willenskraft, Geschwindigkeit?

**Comment by ShikamaNikos** [comment]
Ausdauer Regenerieren wie wann wie viel?
Verteidigungsmalus wenn mehrere einen angreifen?
